### ISSUE TITLE
Why cant i import from scapy?

### ISSUE THREAD

**Issue by Bazaltic** [JustNao/DofusHelper#2]
D:\Dofus Py\DofusHelper-main>py main.py
Initializing sniffer ...
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from sniffer import network
  File "D:\Dofus Py\DofusHelper-main\sniffer\network.py", line 22, in <module>
    from scapy.all import plist, conf
ImportError: cannot import name 'plist' from 'scapy.all' (C:\Users\Tomek\AppData\Local\Programs\Python\Python38\lib\site-packages\scapy-git_archive.dev36448129bf-py3.8.egg\scapy\all.py)

**Comment by JustNao** [comment]
Should be the scapy package version. Most recent ones had their architecture changed, you need an older one.
Though that wouldn't make the whole thing work anyway; Ankama changes a lot of their packet ids each minor update, which require a manual (at least on my part) extraction of the game files to update the whole thing, and some tweaks here and there in the code that shouldn't be necessary but i can't be bothered to optimize it. That means the scripts basically only work whenever i'm playing (and updating it), which is not that often.
You can update it yourself via the DofusInvoker.swf file in the game directory, which you can extract with one of the scripts of `[LaBot](https://github.com/louisabraham/LaBot)`.

**Comment by Bazaltic** [comment]
That was right. 2.4.2 Scappy worked
