### ISSUE TITLE
Price Listing ne fonctionne pas

### ISSUE THREAD

**Issue by chuuyu** [JustNao/DofusHelper#3]
Bonjour, j'ai tenter d'utiliser ton projet et il ne se passe rien quand je lance la fonctionnalité Price Listing (j'ai clean le json du repo, j'ai ouvert l'HDV dans le client et j'ai activé la feature).

Dans la console il n'y a pas d'activité

```
Initializing sniffer ...
Sniffer initiliazed !
Importing sources ...
Sources imported !
2060
0
Module started !
```

**Comment by JustNao** [comment]
Les IDs de packet sont changés par Ankama très fréquemment, donc pour que les scripts marchent il faut que la config soit à jour. Je le fais quand je joue, mais c'est très irrégulier.Je mettrai le Readme à jour pour prévenir les prochains.Si tu as la foi tu peux utiliser les scripts de LaBot (il y a un lien en bas du Readme) pour mettre toi-même à jour le protocole.pk (où il y a les IDs).On Jul 28, 2021 21:12, chuuyu ***@***.***> wrote:

Bonjour, j'ai tenter d'utiliser ton projet et il ne se passe rien quand je lance la fonctionnalité Price Listing (j'ai clean le json du repo, j'ai ouvert l'HDV dans le client et j'ai activé la feature).

Dans la console il n'y a pas d'activité

Initializing sniffer ...

Sniffer initiliazed !

Importing sources ...

Sources imported !

2060

0

Module started !

**Comment by chuuyu** [comment]
Merci pour les indications, je vais regardé pour mettre à jour le protocole
