### ISSUE TITLE
prob!

### ISSUE THREAD

**Issue by yoyok7l** [JustNao/DofusHelper#5]
hi i keep getting this error please help in the treasure bot
AttributeError: 'TreasureHuntHelper' object has no attribute 'movePos' !!!!!
![ok](https://user-images.githubusercontent.com/89700744/131230988-b4f04b12-18b6-4d58-99ae-c2f176fc1ff3.png)

**Comment by JustNao** [comment]
I actually haven't used the TreasureHuntHelper for quite a while, i'll look into it. For now the TreasureHuntBot works, so you can use that.

**Comment by yoyok7l** [comment]
i actually get this problem when i use the bot and not the helper 
but for some reason it says the helper !

**Comment by yoyok7l** [comment]
the treasurehunthelper works well for me , this problem i get it when i use the BOT :(

**Comment by JustNao** [comment]
Are you sure you're using the latest version and haven't changed anything ? Otherwise tell me the exact scenario and i'll try to reproduce it tomorrow, that shouldn't happen if you use the bot option

**Comment by yoyok7l** [comment]
yes i just downloaded it today for the first time, so latest update 
ok so i launch the treasure hunt with the bot and this is everything i see .
![notmoving](https://user-images.githubusercontent.com/89700744/131232511-7e0008f9-1baa-403e-9c99-23ef6752bfd7.png)
so basically the bot doesnt move at all .
thank you for your fast replies !

**Comment by yoyok7l** [comment]
and i didnt change anything at all

**Comment by yoyok7l** [comment]
also i noticed i keep getting this error 

           Error : please keep your Dofus window open for the initilization. You need to restart.

**Comment by yoyok7l** [comment]
even tho dofus is open

**Comment by JustNao** [comment]
Ah, that's the problem. The movePos attribute is defined _after_ checking for the bottom of the screen. It's needed for the click. It uses a png to locate the top side of the spell bar, which you can find at sources/img/pixel/bottomScreen.png. Either make sure that you're having the same thing displayed, so same theme and first page, or change it yourself to something to your liking.

**Comment by Etwenn** [comment]
Salut, j'ai le même soucis du " Error : please keep your Dofus window open for the initilization. You need to restart."
ça marchait au début quand j'ai utilisé le bot, et là plus moyen de faire marcher le HuntBot (les déplacements automatique)
pourtant j'ai pas touché au thème (toujours le thème noir) et je suis bien à la page 1 sur mon jeu :/
Edit : il fonctionne de temps en temps j'ignore pourquoi, là j'ai réussi à le faire fonctionner, mais le déplacement vers les cases en haut ne fonctionne pas car il clic trop haut sur l'interface (genre dans la barre de la fenêtre et pas dans la zone de jeu)
Edit2 : J'ai ajuster le "top": (self.sizeX/2, 10) à "top": (self.sizeX/2, 25) et ça fonctionne, je comprend pas pourquoi c'était réglé à 10, j'imagine que tu dois avoir une barre de fenêtre en haut plus "fine" que la mienne ? 
Edit3 : T'estimes à combien de temps le fait de se pencher un peu sur le code & d'implémenter un truc qui clic auto sur le boutton "loupe" une fois les indices récoltés + qui utilise un popo de rappel faisant revenir au zaap des champs de cania pour aller chercher une chasse au trésor auto ? (enfait tout automatiser sauf le combat)

**Comment by JustNao** [comment]
Pour l'erreur de l'initialization, le problème vient de l'image utilisée pour localiser le bas de l'écran. Comme l'interface peut être bougée à souhait, c'est le moyen le plus simple mais bourrin que j'ai trouvé pour placer le click vers le bas. Ça prend le centre de l'image et ça décale de 10 pixels vers le haut. Tu peux tout à fait reprendre un screenshot de ton interface pour être sûr que ça marche.

Pour le problème de position au top, oui c'est normal, je joue en plein écran.

Normalement ça click déjà sur le bouton loupe une fois les indices récoltés, vérifie si à ce moment y'a pas un message "No next step detected, need to do it manually", c'est que l'image n'a pas pu être trouvée. Encore une fois, tu peux modifier l'image pour que ça marche bien avec ton écran (on va pas se mentir la compatibilité inter-client n'était pas une priorité quand j'ai fait ce bot).
Pour la popo de rappel c'est délicat, le sniffer se met en pause automatiquement à la fin de la chasse pour ne pas être en route pendant le combat. Certains packets en combat sont très mal gérés, et font crasher le sniffer. Il fallait que je répare ça (dans les prochaines semaines ça sera au moins faisable de le laisser pendant les combats). D'ici là tu ne peux pas/rarement le laisser ouvert pendant le combat, donc aucun moyen de détecter la fin du combat. Après une fois que ça c'est réglé, c'est juste une histoire de détecter le packet correspondant à la fin du combat, et à appuyer sur ton raccourci pour la popo de rappel.

**Comment by Etwenn** [comment]
Hello (oui je ré apparait après 10 jours ^^)
J'ai fais un truc pour détecter les dimensions du client et de générer des images en fonction de la résolution pour pouvoir bien utiliser les locate() de la librairie de détection (pour les boutons, les jalons etc...)
ça marche pas trop trop mal quand on est pas en full screen mais aussi en demi screen quand tu veux faire autre chose à côté
Si t'es intéressé je pourrai te faire une MR ou quoi même si je t'avoue le code est pas ultra propre
J'ai fait un petit test intéressant genre de mettre le bot dans un vm (genre virtalBox) et ça marche pas trop mal non plus, ça permet de faire complètement autre chose à côté, voir d'utiliser plusieurs bots en même temps. J'ai commencé à me pencher sur automatiser le début de la chasse au trésor (genre aller au zaap, et en prendre une automatiquement puis prendre le zaap le plus proche) mais je manque un peu de temps ces temps ci
et je me demandais il y a une maj aujourd'hui, et je crois que j'ai besoin d'un peu d'aide pour récupérer l'id des nouveaux paquets, je suis moins à l'aise avec ça, si tu pourrai me montrer (ou me dire ?) si tu as le temps. Mon discord : Wewen#4057

**Comment by JustNao** [comment]
Je joue uniquement en full screen et un peu la flemme de gérer ça en ce moment, mais libre à toi de fork le repo et de changer tes trucs, j'y jetterai un coup d'oeil un de ces quatres ;).
Sinon pour les maj je vais le mettre ici et plus tard dans le Readme, comme ça tout le monde pourra en profiter.

My process for extracting packet IDs (every script used is from [Labot](https://github.com/louisabraham/LaBot)) :
1. Decompile the DofusInvoker.swf using [decompile.sh](https://github.com/louisabraham/LaBot/blob/master/scripts/decompile.sh) (I've come to use the .sh even on windows using bash, as the .bat didn't work properly for me). You may need to modify the Dofus folder and/or the location of the ffdec depending on the OS. On Windows, don't forget to put the path to ffdec.exe in double quotes. 
This will decompile every packet file into the sources folder
2. Build the protocol.pk using [build_protocol.py](https://github.com/louisabraham/LaBot/blob/master/scripts/build_protocol.py)
3. Replace the old protocol.pk with the new protocol.pk that was created in the labot folder

**Comment by Etwenn** [comment]
Oky, je te préviendrai quand j'aurais suffisement avancé !

ça marche nickel de mon côté l'extraction et le remplacement du .pk

**Comment by Etwenn** [comment]
Hello, après une petite abscence j'ai retenté de maj le protocol.pk, 
je décompile sans problème,
et à la fin du build_protocol.py j'ai ça : 
![image](https://user-images.githubusercontent.com/50783198/140191290-a03737bf-7600-4914-af81-3e007cb3f399.png)

tu sais d'où ça pourrait provenir ?

**Comment by JustNao** [comment]
Pour une raison que j'ignore totalement, le packet `ShortcutBarAddRequestMessage` a un ID de `2`, qui normalement est pour les `NetworkDataContainerMessage`. Pour être honnête j'ai aucune idée de son utilité, et il est pas utilisé dans mes scripts donc à moins que tu l'utilise te casse pas la tête et supprime ce packet `LaBot/sources/scripts/com/ankamagames/dofus/network/messages/game/shortcut/ShortcutBarAddRequestMessage.as`. Cela ne devrait pas poser de problème, dans mes souvenirs j'avais implémenté un fail-safe pour les IDs non reconnus.
