### ISSUE TITLE
build_protocol.py | assert protocolId not in msg_from_id

### ISSUE THREAD

**Issue by Brotove** [JustNao/DofusHelper#6]
Salut, j'éspere que vous allez bien.
J'ai essayer de créer comme vous cité dans readme le protocol.pk avec le [build_protocol.py](https://github.com/louisabraham/LaBot/blob/master/scripts/build_protocol.py) de la bot apres avoir decompiler le Dofusinvoker.swf.
le probléme je lance le [build_protocol.py](https://github.com/louisabraham/LaBot/blob/master/scripts/build_protocol.py) il s'arrete avec cette erreur assertion, peut-étre vous aurais une solution svp merci 

Traceback (most recent call last):
  File "E:\*\Games\Gérer\Scripts\python\LaBot-master\scripts\build_protocol.py", line 194, in <module>
    build()
  File "E:\*\Games\Gérer\Scripts\python\LaBot-master\scripts\build_protocol.py", line 167, in build
    parse(t)
  File "E:\*\Games\Gérer\Scripts\python\LaBot-master\scripts\build_protocol.py", line 147, in parse
    assert protocolId not in msg_from_id
AssertionError

**Comment by JustNao** [comment]
Encore un problème de protocol qui a un ID déjà utilisé, je sais pas trop d'où ça vient. Mets à jour ta version de DofusHelper, j'ai ajouté un decompile.sh et build_protocol.py mis à jour pour ne pas avoir à jongler entre LaBot et DofusHelper, et ajouté une option sur le builder pour skip les IDs dupliqués (ce qui n'est pas du tout une bonne solution, mais on verra un jour pour ça).

**Comment by Brotove** [comment]
> Encore un problème de protocol qui a un ID déjà utilisé, je sais pas trop d'où ça vient. Mets à jour ta version de DofusHelper, j'ai ajouté un decompile.sh et build_protocol.py mis à jour pour ne pas avoir à jongler entre LaBot et DofusHelper, et ajouté une option sur le builder pour skip les IDs dupliqués (ce qui n'est pas du tout une bonne solution, mais on verra un jour pour ça).

Merci bcp pour votre efforts ça passe bien le maj, bonne journée
