### ISSUE TITLE
Nouveau 

### ISSUE THREAD

**Issue by Etwenn** [JustNao/DofusHelper#7]
Hello Nao, je revient jouer de temps en temps, 
je me demandais suite à une mise à jour peut-être debut 2022 (?)
Les POI de chasse au trésor ont énormement augmenté
Beaucoup ne figure pas dans le fichier PointOfInterest.json de ton project 
J'ai trouvé PointOfInterest.d2o dans les fichiers de Dofus,
suffirait-il à le décompiler et le remplacer par l'ancien ?

**Comment by JustNao** [comment]
PointOfInterest.json n'est pas utilisé pour les chasses (c'était pour des tests il y a longtemps), donc le manque de POI n'est pas important. Le problème qui peut arriver c'est que les indices de chasse aux trésors soient manquants/mal placés. Ça vient de dofus-map, que j'utilise pour chopper les positions.

Le site n'est pas vraiment tenu à jour (en tout cas la base de données des indices), et plus les mises à jour du jeu arrivent plus ça empire. Un autre site permet d'avoir des indices à jour (dofusdb.fr). Par contre j'ai entendu dire qu'ils allaient possiblement bloquer leur API dans un futur proche, donc je suis en train de scanner chaque map du jeu pour stocker la position de tous les indices (mis à jour à la dernière version du coup).

En conclusion, si le manque d'indices de dofus-map pose vraiment problème tu peux changer par toi-même l'implementation de la recherche d'indices pour passer par dofusdb. Sinon, j'ai une petite maj du bot en préparation qui va améliorer grandement la précision des indices et ajouter plusieurs fallbacks en cas de faux négatifs qui devrait arriver dans les prochaines semaines si j'ai le temps d'avancer dessus.

**Comment by Etwenn** [comment]
Re, j'ai scrappé dofusDB, si tu souhaites le fichier : https://justbeamit.com/qusvk
(Il est structuré comme ça : 
"x/y" {
  0 : {indicesID : distance, indicesId : distance}
  2 : {indicesId : distnace}
  ...
}

avec 0,2,4,6 étant les directions

Pas sur à 100% qu'il soit complet complet (possible requête en erreur réseau durant le scraping)

De ce que j'ai entendu dire, il risque d'y avoir beaucoup de nouveau indices à la prochaines mise à jour (2.64.x)

**Comment by JustNao** [comment]
Ils ont implémenté un système de token qui empêche d'utiliser facilement leur API. Pour l'instant j'utilise un navigateur pour simuler les clics d'un utilisateur. Un peu plus lent que passer par l'API directement mais ça passe bien, et permet de rester à jour avec les nouvelles MAJs.
