### ISSUE TITLE
Sniffer error

### ISSUE THREAD

**Issue by Brotove** [JustNao/DofusHelper#8]
Salut Nao, j'utilise nomansland mais apres la maj le sniffer ne capture plus les packets lorsque je print les protocolId rien ne s'affiche dans le console j'ai update le protocol.pk sauf que rien ne se passe avant ça a marché nickel, un grand merci pour cette outils

**Comment by JustNao** [comment]
Oulah le nomansland est un script que j'utilise pour debug ou tester des nouveaux trucs à l'arrache, il est pas tenu à jour et va changer très souvent (je savais même pas qu'il était sur le git, je croyais l'avoir mis dans le gitignore). Si pour une quelconque raison tu as besoin de ce que j'ai fait dans ce script poubelle, tu peux retrouver les anciennes versions avec Github. Si ça change rien, rollback la maj du sniffer. Si ça change toujours rien, redis moi et je regarderai ça.

**Comment by Brotove** [comment]
merci pour votre rapide reponse je vais essayé se que vous venez de dire, après je vous confirme si c'est ok 
si il marche de ton coté veuillez le confirmé a tal

**Comment by Brotove** [comment]
Non le sniffer ne capture plus comme avant lorsque je `print(protocol.msg_from_id[msg.id]['name'], msg.id, sep=", ")` rien ne s'affiche dans le console j'utilise bien scapy dans requirements

**Comment by Brotove** [comment]
Désolé pr le spam mais voila le resultat du console
`Sniffer initiliazed !
Importing sources ...
Sources imported !
Flushing buffers
Module started !
CharacterAlignmentWarEffortProgressionMessage, 9744
CharacterAlignmentWarEffortProgressionMessage, 9744
Weird packet found, flushing
GuildFightPlayersEnemiesListMessage, 9474`
packet sans aucun rapport avec atelier du forgemage

**Comment by JustNao** [comment]
Est-ce que tu as testé un autre module pour voir si ça venait uniquement de l'outil forgemagie ? Je peux pas travailler sur ça en ce moment. Pour l'instant c'est mit de côté et je reprendrai dessus peut-être plus tard cette année.

**Comment by Brotove** [comment]
non tt les modules ça a marché avant mais plus maintenant je ne sais pas si c le sniffer ou le decodeur qui lache

**Comment by Brotove** [comment]
Bonjour j'ai essayer chaque module dans  `def packetRead` la ligne `print(protocol.msg_from_id[msg.id]['name'], msg.id, sep=", ")` tout les modules print dans le console `Sniffer initiliazed ! Importing sources ... Sources imported ! Flushing buffers Module started ! CharacterAlignmentWarEffortProgressionMessage, 9744 CharacterAlignmentWarEffortProgressionMessage, 9744 Weird packet found, flushing GuildFightPlayersEnemiesListMessage, 9474` seulement lorsque je change de map sinon ça n'affiche rien dans le console

**Comment by JustNao** [comment]
J'ai tout mis à jour et ça refonctionne bien. Ton problème venait sûrement de sources pas mises à jour.
