### ISSUE TITLE
Chasse au trésor 

### ISSUE THREAD

**Issue by ELO-I** [JustNao/DofusHelper#9]
Salut Nao,
Je souhaitais test ce fameux treasur hunt bot,
Cependant lorsque je le lance il ne se passe rien,
Et dès le lancement j'ai une erreur comme quoi je dois relancer .
Peut être y a t'il des prérequis ou bien des éléments à placer quelque part ?
Pourrait tu m'éclairer ? 
Merci :)
![image](https://user-images.githubusercontent.com/79156755/179426703-a55205ad-68b8-49d7-ba9a-4780c2f3c4dc.png)
![image](https://user-images.githubusercontent.com/79156755/179426721-b662fe6c-fbaf-4e8b-b067-cabcba4dd5d0.png)

**Comment by Brotove** [comment]
salut, peut-etre que tu dois changer l'image DofusHelper/tree/main/sources/img/pixe/bottomScreen.png par la votre on plus ça ne marche sans réparer le sniffer car il ne trouve que "weird packet"

**Comment by ELO-I** [comment]
Merci de ta réponse, mais il ne ce passe rien quand je lance le helper ou le bot, nada, j'ai bien changé l'image de bottom
![image](https://user-images.githubusercontent.com/79156755/179574598-25058f1a-3823-4139-a9da-8d2846f0fe48.png)
![image](https://user-images.githubusercontent.com/79156755/179574978-445a26a5-abd5-4c8d-82a0-7ff0f996b3c2.png)

Peut être que j'ai mal fait un truc ou alors il y a une manipulation à faire pour l'initialisation ?

**Comment by Brotove** [comment]
non, je suis un noob dans Python il faut mettre peut-étre a jour packetRead on a qu'attendre @JustNao a l'update grand merci a lui pour cette outil

**Comment by ELO-I** [comment]
Alors pour info,
Je viens de changer les Id je pense,
Lors du décompilage j'ai environ 1600 et quelque paquets,
Et lors du build 1496 je ne sais pas si c'est normal mais voilà,
Le bot ne fonctionne toujours pas,
![image](https://user-images.githubusercontent.com/79156755/179588970-3f01ce59-7a28-43f3-a4da-1a24c0a5d47d.png)

**Comment by JustNao** [comment]
Pas assez d'infos pour vraiment savoir d'où vient le problème initial. Dans tous les cas, j'ai mis à jour le bot et il fonctionne de mon côté. Relisez bien le README qui a été mis à jour pour l'installation.
